runtime: nodejs10
handlers:
# catch all handler to index.html
- url: /
  static_files: dist/index.html
  upload: dist/index.html
# Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
  # Serve all static files with urls ending with a file extension
- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
